# I. Numpy

### Импортируйте NumPy

In [2]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [8]:
a = np.zeros(10)
a[4] = 1
b = a.reshape(2,5)
b

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [13]:
a = np.arange(10,50)
b = a[::-1]
b
mask = b % 2 ==0
b[mask]

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [5]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [8]:
a = np.random.randint(0,10, (4,3,2))
a

array([[[4, 3],
        [8, 6],
        [5, 6]],

       [[3, 3],
        [7, 5],
        [2, 2]],

       [[9, 8],
        [9, 5],
        [9, 3]],

       [[0, 8],
        [4, 1],
        [9, 2]]])

### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [14]:
a = np.arange(24).reshape(6,4)
b = np.arange(12).reshape(4,3)
c = a.dot(b)
c

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262],
       [258, 312, 366],
       [330, 400, 470],
       [402, 488, 574]])

### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [17]:
a = np.random.randint(0,10, (7,7))
# среднее отклонение
mediann = a.mean()

# стандартное отклонение
standart = np.std(a)

# нормализация
norm = np.linalg.norm(a)
norm_total = np.sum([val/norm for val in a ])

print(mediann)
print(standart)
print(norm_total)

4.163265306122449
2.90212405517984
5.742493204975672


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

### Загрузите датасет Tips из набора датасетов seaborn

### Посмотрите на первые 5 строчек

### Узнайте сколько всего строчек и колонок в данных

### Проверьте есть ли пропуски в данных

### Посмотрите на распределение числовых признаков

### Найдите максимальное значение 'total_bill'

### Найдите количество курящих людей

### Узнайте какой средний 'total_bill' в зависимости от 'day'

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.